engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - app/**
exclude_paths:
  - app/**/*.spec.js
  - app/**/*.e2e.js
  - app/lang/**
