language: node_js

node_js:
  - "5.1"
  - "5.0"
  - "4.2"
  - "0.12"

before_install:
  - npm install -g bower
  - bower install

script:
  - gulp ci
 - 'if [ "${TRAVIS_NODE_VERSION}" = "5.1" ]; then gulp protractor ; fi'

after_script:
 - 'if [ "${TRAVIS_NODE_VERSION}" = "4.1" ]; then npm install codeclimate-test-reporter && codeclimate-test-reporter < coverage/lcov/lcov.info ; fi'

env:
  global:
  - SAUCE_USERNAME=seblucas
  - secure: VVxocvmz6WYr3tZSTA42M/LUhaHoBWw5onh85hnquoMaxspd3tDCyfQIowTTmEXikRh2T0CkTH7X3dhVwRTd/Ha9isja1qDo9Lc2flGCoWICF7WFZuom084+d+O+EWx4WZMAw4Lz4w6a5xflpPKnzNs9B0+de0BdTlQ5qSXVrcA=
addons:
  sauce_connect: true
  hosts:
    - cops-travis

cache:
  directories:
    - node_modules
