language: node_js

matrix:
  include:
    - node_js: "5.1"

    - node_js: "5.0"

    - node_js: "4.2"
      addons:
        sauce_connect: true
        hosts:
          - cops-travis

    - node_js: "0.12"

before_install:
  - npm install -g bower
  - bower install

script:
  - gulp ci
  - 'if [ "${TRAVIS_NODE_VERSION}" = "4.2" ]; then gulp protractor ; fi'

after_script:
 - 'if [ "${TRAVIS_NODE_VERSION}" = "4.2" ]; then npm install codeclimate-test-reporter && codeclimate-test-reporter < coverage/lcov/lcov.info ; fi'

env:
  global:
    - SAUCE_USERNAME=seblucas



cache:
  directories:
    - node_modules
