language: node_js

node_js:
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"

before_install:
  - npm install -g bower
  - bower install

script:
  - gulp ci

after_script:
 - 'if [ "${TRAVIS_NODE_VERSION}" = "4.1" ]; then npm install codeclimate-test-reporter && codeclimate-test-reporter < coverage/lcov/lcov.info ; fi'
