language: node_js

matrix:
  include:
    - node_js: "5"

    - node_js: "4.2"
      addons:
        sauce_connect: true
        hosts:
          - cops-travis

before_install:
  - npm install -g bower
  - bower install

script:
  - gulp ci
  - 'if [ "${TRAVIS_NODE_VERSION}" = "4.2" ]; then gulp protractor ; fi'

after_script:
 - 'if [ "${TRAVIS_NODE_VERSION}" = "4.2" ]; then npm install codeclimate-test-reporter && codeclimate-test-reporter < coverage/lcov/lcov.info ; fi'

env:
  global:
    - SAUCE_USERNAME=sauce-cops-html-ui



cache:
  directories:
    - node_modules

before_deploy:
  - gulp archive

deploy:
  provider: releases
  api_key:
    secure: hRDnJJudpZ++GCnMD8uih9xScfYD7gWQW7RsklmUh7f1WWpqNSohyUOMWyuHw7Uh3TgjaXAGDwv0jUpAj/rnHj0C6zh2PVAAoKcg5rFo6PoJmeNxpFfQHgx3sdikUoPW1rtBmqJQNodSy+WnO2NF12YzDtgzgL83sk728HB33cI=
  file: cops-html-ui.zip
  on:
    repo: seblucas/cops-html-ui
    tags: true
    node_js: "4.2"

